services:
  chromadb:
    image: chromadb/chroma:0.6.3
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=FALSE
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - /tmp/chroma:/tmp/chroma

  llm:
    build:
      context: ./llama.cpp
      dockerfile: Dockerfile.server
    container_name: llama-server
    command: >
      --model /models/mistral-7b-q4.gguf
      --port 11434
      --ctx-size 256
      --threads 1
    volumes:
      - ./models:/models
    ports:
      - "11434:11434"
    restart: unless-stopped

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chromadb
      - llm
    environment:
      - RUST_LOG=info
      - MCP_ENV=development
      - CHROMADB_URL=http://chromadb:8000
      - CHROMA_COLLECTION_ID=1414cedf-3081-4235-ab29-656549bdff1a
      - LLM_URL=http://llm:11434
    ports:
      - "8080:8080"
    volumes:
      - ./agent.sent:/usr/src/app/agent.sent
      - ./memory.db:/usr/src/app/memory.db
    command: >
      sh -c "cargo run --release"
