version: "3.9"

services:
  mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MCP_ENV=production
      - DATABASE_URL=sqlite:memory.db
      - CHROMADB_URL=http://chromadb:8000
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:0.6.3
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=TRUE
